openapi: 3.0.0
info:
  title: rongwj666/weixin-java-miniapp-demo
  version: 1.0.0
  description: rongwj666/weixin-java-miniapp-demo
servers:
- url: http://localhost:8080
  description: Local development server
paths:
  /wx/media/{appid}/upload:
    post:
      tags:
      - WxMaMediaController
      summary: uploadMedia
      description: 该代码是一个处理文件上传的Spring接口，验证appid后接收多文件请求，将文件暂存并上传至微信服务器，返回媒体ID列表，最后清理线程本地变量。
      operationId: weixin-java-miniapp-demo_com.github.binarywang.demo.wx.miniapp.controller.WxMaMediaController#uploadMedia
      parameters:
      - in: path
        name: appid
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      deprecated: false
  /wx/media/{appid}/download/{mediaId}:
    get:
      tags:
      - WxMaMediaController
      summary: getMedia
      description: Java方法：通过appid和mediaId下载微信媒体文件，验证配置后返回文件并清理ThreadLocal。
      operationId: weixin-java-miniapp-demo_com.github.binarywang.demo.wx.miniapp.controller.WxMaMediaController#getMedia
      parameters:
      - in: path
        name: appid
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
      deprecated: false
  /wx/user/{appid}/login:
    get:
      tags:
      - WxMaUserController
      summary: login
      description: 这是一个微信小程序登录接口，通过code获取用户session信息。验证code非空和appid有效性后，返回包含sessionKey和openid的JSON。异常时返回错误信息，最后清理ThreadLocal。
      operationId: weixin-java-miniapp-demo_com.github.binarywang.demo.wx.miniapp.controller.WxMaUserController#login
      parameters:
      - in: path
        name: appid
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
      deprecated: false
  /wx/user/{appid}/info:
    get:
      tags:
      - WxMaUserController
      summary: info
      description: 该代码是一个微信小程序后端接口，用于验证用户信息并解密返回用户数据。首先检查appid配置，然后校验用户信息签名，最后解密数据并返回JSON格式的用户信息。
      operationId: weixin-java-miniapp-demo_com.github.binarywang.demo.wx.miniapp.controller.WxMaUserController#info
      parameters:
      - in: query
        name: userId
        required: true
        description: ''
        schema:
          type: string
      - in: query
        name: offset
        required: true
        description: ''
        schema:
          type: integer
          format: int32
      - in: path
        name: appid
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
      deprecated: false
  /wx/user/{appid}/phone:
    get:
      tags:
      - WxMaUserController
      summary: phone
      description: 获取微信手机号接口：校验appid和用户信息，解密手机号数据并返回。失败返回错误信息，成功返回手机号JSON。
      operationId: weixin-java-miniapp-demo_com.github.binarywang.demo.wx.miniapp.controller.WxMaUserController#phone
      parameters:
      - in: query
        name: limit
        required: true
        description: ''
        schema:
          type: integer
          format: int32
      - in: path
        name: appid
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
      deprecated: false
  /wx/portal/{appid}:
    get:
      tags:
      - WxPortalController
      summary: authGet
      description: 这是一个处理微信认证的GET接口，验证签名参数后返回echostr或错误信息，包含参数校验和ThreadLocal清理。
      operationId: weixin-java-miniapp-demo_com.github.binarywang.demo.wx.miniapp.controller.WxPortalController#authGet
      parameters:
      - in: path
        name: appid
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
      deprecated: false
    post:
      tags:
      - WxPortalController
      summary: post
      description: 处理微信请求的POST接口，验证appid并解析明文或AES加密的XML/JSON消息，路由处理后返回成功或错误。
      operationId: weixin-java-miniapp-demo_com.github.binarywang.demo.wx.miniapp.controller.WxPortalController#post
      parameters:
      - in: path
        name: appid
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
      deprecated: false
  /error/404:
    get:
      tags:
      - ErrorController
      summary: error404
      description: 这是一个Spring MVC的GET请求处理方法，路径为"/404"，返回字符串"error"。
      operationId: weixin-java-miniapp-demo_com.github.binarywang.demo.wx.miniapp.error.ErrorController#error404
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
      deprecated: false
  /error/500:
    get:
      tags:
      - ErrorController
      summary: error500
      description: 这是一个Spring MVC的GET请求处理方法，映射路径为"/500"，返回字符串"error"。
      operationId: weixin-java-miniapp-demo_com.github.binarywang.demo.wx.miniapp.error.ErrorController#error500
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
      deprecated: false
components: {}
